// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaptureScreenshotRequest {
    #[prost(int32, tag = "1")]
    pub employee_id: i32,
    #[prost(string, tag = "2")]
    pub session_token: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", tag = "4")]
    pub screenshot_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag = "5")]
    pub compression_type: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaptureScreenshotResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub screenshot_id: i64,
    #[prost(string, tag = "4")]
    pub file_path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetScreenshotsRequest {
    #[prost(int32, tag = "1")]
    pub employee_id: i32,
    #[prost(string, tag = "2")]
    pub session_token: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub start_date: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub end_date: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "6")]
    pub limit: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub offset: ::core::option::Option<i32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetScreenshotsResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub screenshots: ::prost::alloc::vec::Vec<ScreenshotInfo>,
    #[prost(int32, tag = "4")]
    pub total_count: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteScreenshotRequest {
    #[prost(int32, tag = "1")]
    pub employee_id: i32,
    #[prost(string, tag = "2")]
    pub session_token: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub screenshot_id: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteScreenshotResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetScreenshotRequest {
    #[prost(int32, tag = "1")]
    pub employee_id: i32,
    #[prost(string, tag = "2")]
    pub session_token: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub screenshot_id: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetScreenshotResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub screenshot: ::core::option::Option<ScreenshotData>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScreenshotInfo {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int32, tag = "2")]
    pub employee_id: i32,
    #[prost(int64, optional, tag = "3")]
    pub activity_log_id: ::core::option::Option<i64>,
    #[prost(string, tag = "4")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub file_path: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub file_size: i32,
    #[prost(string, tag = "7")]
    pub compression_type: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScreenshotData {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int32, tag = "2")]
    pub employee_id: i32,
    #[prost(int64, optional, tag = "3")]
    pub activity_log_id: ::core::option::Option<i64>,
    #[prost(string, tag = "4")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub screenshot_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "6")]
    pub file_path: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub file_size: i32,
    #[prost(string, tag = "8")]
    pub compression_type: ::prost::alloc::string::String,
}
